eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8764

spring:
  application:
    name: service-consumer

feign:
  hystrix:
    #此项不为true，feign断路器不生效
    #idea会报错找不到，应该是idea的原因
    enabled: true
  compression:
    request:
      # 配置请求GZIP压缩
      enabled: true
      # 配置压缩支持的MIME TYPE
      mime-types: text/xml,application/xml,application/json
      # 配置压缩数据大小的下限
      min-request-size: 2048
    response:
      # 配置响应GZIP压缩
      enabled: true
#springboot2.0以上base-path为`/actuator`且要设置include属性指定暴露的端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /

