eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    #此项不为true，feign断路器不生效
    #idea会报错找不到，应该是idea的原因
    enabled: true
  compression:
    request:
      # 配置请求GZIP压缩
      enabled: true
      # 配置压缩支持的MIME TYPE
      mime-types: text/xml,application/xml,application/json
      # 配置压缩数据大小的下限
      min-request-size: 2048
    response:
      # 配置响应GZIP压缩
      enabled: true
#springboot2.0以上base-path为`/actuator`
management:
  endpoints:
    web:
      exposure:
        #actuator默认只公开info和health接口，如果需要获取更多信息，则需增加如下配置
        include: "*"
      base-path: /

spring:
  rabbitmq:
    host: localhost
    port: 5672

testConfig:
  value: 1