eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
        enableSelfPreservation: false
    instance:
        hostname: localhost

server:
    port: 8761
logging:
  level:
    root: info