eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
    port: 8888

spring:
    application:
        name: config-server
    cloud:
        config:
            label: master
            server:
                git:
                    searchPaths: config
                    uri: https://github.com/cumtfc/SpringCloudConfig/
#                    username: your username
#                    password: your password
